version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adonis-invitations
    restart: unless-stopped
    ports:
       - "3333:3333"
    depends_on:
      - db
    volumes:
      - '.:/home/node/app'
      - 'node_modules:/home/node/app/node_modules'
    networks:
      - invitation-network
  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '8081:8080'
    networks:
      - invitation-network
  db:
    image: 'mysql:5.7'
    container_name: db_invitation
    env_file: .env
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$USER_NAME
      - MYSQL_PASSWORD=$USER_PASSWORD
      - MYSQL_ROOT_PASSWORD=ROOT_PASSWORD
    volumes:
      - './data/db:/var/lib/mysql'
    networks:
      - invitation-network
networks:
  invitation-network:
    driver: bridge
volumes:
  node_modules: null
